# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Auth_pb2 as Auth__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/LQTP.AuthService/Login',
                request_serializer=Auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=Auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/LQTP.AuthService/RefreshToken',
                request_serializer=Auth__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=Auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/LQTP.AuthService/Logout',
                request_serializer=Auth__pb2.LogoutRequest.SerializeToString,
                response_deserializer=Auth__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.GetCurrentUser = channel.unary_unary(
                '/LQTP.AuthService/GetCurrentUser',
                request_serializer=Auth__pb2.EmptyResponse.SerializeToString,
                response_deserializer=Auth__pb2.User.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/LQTP.AuthService/ListUsers',
                request_serializer=Auth__pb2.EmptyResponse.SerializeToString,
                response_deserializer=Auth__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/LQTP.AuthService/CreateUser',
                request_serializer=Auth__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=Auth__pb2.User.FromString,
                _registered_method=True)
        self.ChangePassword = channel.unary_unary(
                '/LQTP.AuthService/ChangePassword',
                request_serializer=Auth__pb2.ChangePasswordRequest.SerializeToString,
                response_deserializer=Auth__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.ResetUserPassword = channel.unary_unary(
                '/LQTP.AuthService/ResetUserPassword',
                request_serializer=Auth__pb2.ResetUserPasswordRequest.SerializeToString,
                response_deserializer=Auth__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.GrantFactorPermission = channel.unary_unary(
                '/LQTP.AuthService/GrantFactorPermission',
                request_serializer=Auth__pb2.GrantFactorPermissionRequest.SerializeToString,
                response_deserializer=Auth__pb2.GrantFactorPermissionResponse.FromString,
                _registered_method=True)
        self.RevokeFactorPermission = channel.unary_unary(
                '/LQTP.AuthService/RevokeFactorPermission',
                request_serializer=Auth__pb2.GrantFactorPermissionRequest.SerializeToString,
                response_deserializer=Auth__pb2.GrantFactorPermissionResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetUserPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantFactorPermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeFactorPermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=Auth__pb2.LoginRequest.FromString,
                    response_serializer=Auth__pb2.LoginResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=Auth__pb2.RefreshTokenRequest.FromString,
                    response_serializer=Auth__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=Auth__pb2.LogoutRequest.FromString,
                    response_serializer=Auth__pb2.EmptyResponse.SerializeToString,
            ),
            'GetCurrentUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentUser,
                    request_deserializer=Auth__pb2.EmptyResponse.FromString,
                    response_serializer=Auth__pb2.User.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=Auth__pb2.EmptyResponse.FromString,
                    response_serializer=Auth__pb2.ListUsersResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=Auth__pb2.CreateUserRequest.FromString,
                    response_serializer=Auth__pb2.User.SerializeToString,
            ),
            'ChangePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangePassword,
                    request_deserializer=Auth__pb2.ChangePasswordRequest.FromString,
                    response_serializer=Auth__pb2.EmptyResponse.SerializeToString,
            ),
            'ResetUserPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetUserPassword,
                    request_deserializer=Auth__pb2.ResetUserPasswordRequest.FromString,
                    response_serializer=Auth__pb2.EmptyResponse.SerializeToString,
            ),
            'GrantFactorPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantFactorPermission,
                    request_deserializer=Auth__pb2.GrantFactorPermissionRequest.FromString,
                    response_serializer=Auth__pb2.GrantFactorPermissionResponse.SerializeToString,
            ),
            'RevokeFactorPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeFactorPermission,
                    request_deserializer=Auth__pb2.GrantFactorPermissionRequest.FromString,
                    response_serializer=Auth__pb2.GrantFactorPermissionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LQTP.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LQTP.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.AuthService/Login',
            Auth__pb2.LoginRequest.SerializeToString,
            Auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.AuthService/RefreshToken',
            Auth__pb2.RefreshTokenRequest.SerializeToString,
            Auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.AuthService/Logout',
            Auth__pb2.LogoutRequest.SerializeToString,
            Auth__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.AuthService/GetCurrentUser',
            Auth__pb2.EmptyResponse.SerializeToString,
            Auth__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.AuthService/ListUsers',
            Auth__pb2.EmptyResponse.SerializeToString,
            Auth__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.AuthService/CreateUser',
            Auth__pb2.CreateUserRequest.SerializeToString,
            Auth__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.AuthService/ChangePassword',
            Auth__pb2.ChangePasswordRequest.SerializeToString,
            Auth__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetUserPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.AuthService/ResetUserPassword',
            Auth__pb2.ResetUserPasswordRequest.SerializeToString,
            Auth__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GrantFactorPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.AuthService/GrantFactorPermission',
            Auth__pb2.GrantFactorPermissionRequest.SerializeToString,
            Auth__pb2.GrantFactorPermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeFactorPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.AuthService/RevokeFactorPermission',
            Auth__pb2.GrantFactorPermissionRequest.SerializeToString,
            Auth__pb2.GrantFactorPermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
