# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Factor_pb2 as Factor__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Factor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FactorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeFactor = channel.unary_unary(
                '/LQTP.FactorService/AnalyzeFactor',
                request_serializer=Factor__pb2.FactorAnalysisRequest.SerializeToString,
                response_deserializer=Factor__pb2.FactorAnalysisResponse.FromString,
                _registered_method=True)
        self.RunFactor = channel.unary_unary(
                '/LQTP.FactorService/RunFactor',
                request_serializer=Factor__pb2.RunFactorRequest.SerializeToString,
                response_deserializer=Factor__pb2.RunFactorResponse.FromString,
                _registered_method=True)
        self.BatchRunFactor = channel.unary_unary(
                '/LQTP.FactorService/BatchRunFactor',
                request_serializer=Factor__pb2.BatchRunFactorRequest.SerializeToString,
                response_deserializer=Factor__pb2.BatchRunFactorResponse.FromString,
                _registered_method=True)
        self.ListFactorAnalyses = channel.unary_unary(
                '/LQTP.FactorService/ListFactorAnalyses',
                request_serializer=Factor__pb2.ListFactorAnalysesRequest.SerializeToString,
                response_deserializer=Factor__pb2.ListFactorAnalysesResponse.FromString,
                _registered_method=True)
        self.GetFactorAnalysis = channel.unary_unary(
                '/LQTP.FactorService/GetFactorAnalysis',
                request_serializer=Factor__pb2.GetFactorAnalysisRequest.SerializeToString,
                response_deserializer=Factor__pb2.FactorAnalysisRun.FromString,
                _registered_method=True)
        self.ListFactorRankings = channel.unary_unary(
                '/LQTP.FactorService/ListFactorRankings',
                request_serializer=Factor__pb2.ListFactorRankingsRequest.SerializeToString,
                response_deserializer=Factor__pb2.ListFactorRankingsResponse.FromString,
                _registered_method=True)
        self.ListFactors = channel.unary_unary(
                '/LQTP.FactorService/ListFactors',
                request_serializer=Factor__pb2.ListFactorsRequest.SerializeToString,
                response_deserializer=Factor__pb2.ListFactorsResponse.FromString,
                _registered_method=True)
        self.GetFactor = channel.unary_unary(
                '/LQTP.FactorService/GetFactor',
                request_serializer=Factor__pb2.GetFactorRequest.SerializeToString,
                response_deserializer=Factor__pb2.FactorDefinition.FromString,
                _registered_method=True)
        self.PublishFactor = channel.unary_unary(
                '/LQTP.FactorService/PublishFactor',
                request_serializer=Factor__pb2.FactorDefinitionActionRequest.SerializeToString,
                response_deserializer=Factor__pb2.FactorDefinitionActionResponse.FromString,
                _registered_method=True)
        self.DeprecateFactor = channel.unary_unary(
                '/LQTP.FactorService/DeprecateFactor',
                request_serializer=Factor__pb2.FactorDefinitionActionRequest.SerializeToString,
                response_deserializer=Factor__pb2.FactorDefinitionActionResponse.FromString,
                _registered_method=True)
        self.DeleteFactor = channel.unary_unary(
                '/LQTP.FactorService/DeleteFactor',
                request_serializer=Factor__pb2.DeleteFactorRequest.SerializeToString,
                response_deserializer=Factor__pb2.FactorDefinitionActionResponse.FromString,
                _registered_method=True)
        self.UpdatePublishedFactors = channel.unary_unary(
                '/LQTP.FactorService/UpdatePublishedFactors',
                request_serializer=Factor__pb2.UpdatePublishedFactorsRequest.SerializeToString,
                response_deserializer=Factor__pb2.UpdatePublishedFactorsResponse.FromString,
                _registered_method=True)
        self.UpdateFactorValues = channel.unary_unary(
                '/LQTP.FactorService/UpdateFactorValues',
                request_serializer=Factor__pb2.UpdateFactorValuesRequest.SerializeToString,
                response_deserializer=Factor__pb2.FactorUpdateResult.FromString,
                _registered_method=True)
        self.UpdatePublishedFactorDailyIc = channel.unary_unary(
                '/LQTP.FactorService/UpdatePublishedFactorDailyIc',
                request_serializer=Factor__pb2.UpdatePublishedFactorDailyIcRequest.SerializeToString,
                response_deserializer=Factor__pb2.UpdatePublishedFactorDailyIcResponse.FromString,
                _registered_method=True)
        self.ListFactorValues = channel.unary_unary(
                '/LQTP.FactorService/ListFactorValues',
                request_serializer=Factor__pb2.ListFactorValuesRequest.SerializeToString,
                response_deserializer=Factor__pb2.ListFactorValuesResponse.FromString,
                _registered_method=True)
        self.ListFactorDailyIc = channel.unary_unary(
                '/LQTP.FactorService/ListFactorDailyIc',
                request_serializer=Factor__pb2.ListFactorDailyIcRequest.SerializeToString,
                response_deserializer=Factor__pb2.ListFactorDailyIcResponse.FromString,
                _registered_method=True)


class FactorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeFactor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunFactor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchRunFactor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFactorAnalyses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFactorAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFactorRankings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFactors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFactor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishFactor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeprecateFactor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFactor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePublishedFactors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFactorValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePublishedFactorDailyIc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFactorValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFactorDailyIc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FactorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeFactor': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeFactor,
                    request_deserializer=Factor__pb2.FactorAnalysisRequest.FromString,
                    response_serializer=Factor__pb2.FactorAnalysisResponse.SerializeToString,
            ),
            'RunFactor': grpc.unary_unary_rpc_method_handler(
                    servicer.RunFactor,
                    request_deserializer=Factor__pb2.RunFactorRequest.FromString,
                    response_serializer=Factor__pb2.RunFactorResponse.SerializeToString,
            ),
            'BatchRunFactor': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchRunFactor,
                    request_deserializer=Factor__pb2.BatchRunFactorRequest.FromString,
                    response_serializer=Factor__pb2.BatchRunFactorResponse.SerializeToString,
            ),
            'ListFactorAnalyses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFactorAnalyses,
                    request_deserializer=Factor__pb2.ListFactorAnalysesRequest.FromString,
                    response_serializer=Factor__pb2.ListFactorAnalysesResponse.SerializeToString,
            ),
            'GetFactorAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFactorAnalysis,
                    request_deserializer=Factor__pb2.GetFactorAnalysisRequest.FromString,
                    response_serializer=Factor__pb2.FactorAnalysisRun.SerializeToString,
            ),
            'ListFactorRankings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFactorRankings,
                    request_deserializer=Factor__pb2.ListFactorRankingsRequest.FromString,
                    response_serializer=Factor__pb2.ListFactorRankingsResponse.SerializeToString,
            ),
            'ListFactors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFactors,
                    request_deserializer=Factor__pb2.ListFactorsRequest.FromString,
                    response_serializer=Factor__pb2.ListFactorsResponse.SerializeToString,
            ),
            'GetFactor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFactor,
                    request_deserializer=Factor__pb2.GetFactorRequest.FromString,
                    response_serializer=Factor__pb2.FactorDefinition.SerializeToString,
            ),
            'PublishFactor': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishFactor,
                    request_deserializer=Factor__pb2.FactorDefinitionActionRequest.FromString,
                    response_serializer=Factor__pb2.FactorDefinitionActionResponse.SerializeToString,
            ),
            'DeprecateFactor': grpc.unary_unary_rpc_method_handler(
                    servicer.DeprecateFactor,
                    request_deserializer=Factor__pb2.FactorDefinitionActionRequest.FromString,
                    response_serializer=Factor__pb2.FactorDefinitionActionResponse.SerializeToString,
            ),
            'DeleteFactor': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFactor,
                    request_deserializer=Factor__pb2.DeleteFactorRequest.FromString,
                    response_serializer=Factor__pb2.FactorDefinitionActionResponse.SerializeToString,
            ),
            'UpdatePublishedFactors': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePublishedFactors,
                    request_deserializer=Factor__pb2.UpdatePublishedFactorsRequest.FromString,
                    response_serializer=Factor__pb2.UpdatePublishedFactorsResponse.SerializeToString,
            ),
            'UpdateFactorValues': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFactorValues,
                    request_deserializer=Factor__pb2.UpdateFactorValuesRequest.FromString,
                    response_serializer=Factor__pb2.FactorUpdateResult.SerializeToString,
            ),
            'UpdatePublishedFactorDailyIc': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePublishedFactorDailyIc,
                    request_deserializer=Factor__pb2.UpdatePublishedFactorDailyIcRequest.FromString,
                    response_serializer=Factor__pb2.UpdatePublishedFactorDailyIcResponse.SerializeToString,
            ),
            'ListFactorValues': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFactorValues,
                    request_deserializer=Factor__pb2.ListFactorValuesRequest.FromString,
                    response_serializer=Factor__pb2.ListFactorValuesResponse.SerializeToString,
            ),
            'ListFactorDailyIc': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFactorDailyIc,
                    request_deserializer=Factor__pb2.ListFactorDailyIcRequest.FromString,
                    response_serializer=Factor__pb2.ListFactorDailyIcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LQTP.FactorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LQTP.FactorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FactorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeFactor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/AnalyzeFactor',
            Factor__pb2.FactorAnalysisRequest.SerializeToString,
            Factor__pb2.FactorAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunFactor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/RunFactor',
            Factor__pb2.RunFactorRequest.SerializeToString,
            Factor__pb2.RunFactorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchRunFactor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/BatchRunFactor',
            Factor__pb2.BatchRunFactorRequest.SerializeToString,
            Factor__pb2.BatchRunFactorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFactorAnalyses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/ListFactorAnalyses',
            Factor__pb2.ListFactorAnalysesRequest.SerializeToString,
            Factor__pb2.ListFactorAnalysesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFactorAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/GetFactorAnalysis',
            Factor__pb2.GetFactorAnalysisRequest.SerializeToString,
            Factor__pb2.FactorAnalysisRun.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFactorRankings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/ListFactorRankings',
            Factor__pb2.ListFactorRankingsRequest.SerializeToString,
            Factor__pb2.ListFactorRankingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFactors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/ListFactors',
            Factor__pb2.ListFactorsRequest.SerializeToString,
            Factor__pb2.ListFactorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFactor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/GetFactor',
            Factor__pb2.GetFactorRequest.SerializeToString,
            Factor__pb2.FactorDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishFactor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/PublishFactor',
            Factor__pb2.FactorDefinitionActionRequest.SerializeToString,
            Factor__pb2.FactorDefinitionActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeprecateFactor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/DeprecateFactor',
            Factor__pb2.FactorDefinitionActionRequest.SerializeToString,
            Factor__pb2.FactorDefinitionActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFactor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/DeleteFactor',
            Factor__pb2.DeleteFactorRequest.SerializeToString,
            Factor__pb2.FactorDefinitionActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePublishedFactors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/UpdatePublishedFactors',
            Factor__pb2.UpdatePublishedFactorsRequest.SerializeToString,
            Factor__pb2.UpdatePublishedFactorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFactorValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/UpdateFactorValues',
            Factor__pb2.UpdateFactorValuesRequest.SerializeToString,
            Factor__pb2.FactorUpdateResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePublishedFactorDailyIc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/UpdatePublishedFactorDailyIc',
            Factor__pb2.UpdatePublishedFactorDailyIcRequest.SerializeToString,
            Factor__pb2.UpdatePublishedFactorDailyIcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFactorValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/ListFactorValues',
            Factor__pb2.ListFactorValuesRequest.SerializeToString,
            Factor__pb2.ListFactorValuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFactorDailyIc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.FactorService/ListFactorDailyIc',
            Factor__pb2.ListFactorDailyIcRequest.SerializeToString,
            Factor__pb2.ListFactorDailyIcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
