# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Portfolio_pb2 as Portfolio__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Portfolio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PortfolioServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePaperPortfolio = channel.unary_unary(
                '/LQTP.PortfolioService/CreatePaperPortfolio',
                request_serializer=Portfolio__pb2.CreatePaperPortfolioRequest.SerializeToString,
                response_deserializer=Portfolio__pb2.PaperPortfolio.FromString,
                _registered_method=True)
        self.ListPaperPortfolios = channel.unary_unary(
                '/LQTP.PortfolioService/ListPaperPortfolios',
                request_serializer=Portfolio__pb2.ListPaperPortfoliosRequest.SerializeToString,
                response_deserializer=Portfolio__pb2.ListPaperPortfoliosResponse.FromString,
                _registered_method=True)
        self.GetPaperPortfolio = channel.unary_unary(
                '/LQTP.PortfolioService/GetPaperPortfolio',
                request_serializer=Portfolio__pb2.GetPaperPortfolioRequest.SerializeToString,
                response_deserializer=Portfolio__pb2.PaperPortfolioDetail.FromString,
                _registered_method=True)
        self.SubmitPaperWeights = channel.unary_unary(
                '/LQTP.PortfolioService/SubmitPaperWeights',
                request_serializer=Portfolio__pb2.SubmitPaperWeightsRequest.SerializeToString,
                response_deserializer=Portfolio__pb2.PaperWeightSubmission.FromString,
                _registered_method=True)
        self.ListPaperPortfolioDailyResults = channel.unary_unary(
                '/LQTP.PortfolioService/ListPaperPortfolioDailyResults',
                request_serializer=Portfolio__pb2.ListPaperPortfolioDailyResultsRequest.SerializeToString,
                response_deserializer=Portfolio__pb2.ListPaperPortfolioDailyResultsResponse.FromString,
                _registered_method=True)
        self.SettlePaperPortfolioDay = channel.unary_unary(
                '/LQTP.PortfolioService/SettlePaperPortfolioDay',
                request_serializer=Portfolio__pb2.SettlePaperPortfolioDayRequest.SerializeToString,
                response_deserializer=Portfolio__pb2.PaperPortfolioDailyResponse.FromString,
                _registered_method=True)
        self.SettleActivePaperPortfolios = channel.unary_unary(
                '/LQTP.PortfolioService/SettleActivePaperPortfolios',
                request_serializer=Portfolio__pb2.SettleActivePaperPortfoliosRequest.SerializeToString,
                response_deserializer=Portfolio__pb2.SettleActivePaperPortfoliosResponse.FromString,
                _registered_method=True)


class PortfolioServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreatePaperPortfolio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPaperPortfolios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaperPortfolio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitPaperWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPaperPortfolioDailyResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SettlePaperPortfolioDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SettleActivePaperPortfolios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PortfolioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePaperPortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePaperPortfolio,
                    request_deserializer=Portfolio__pb2.CreatePaperPortfolioRequest.FromString,
                    response_serializer=Portfolio__pb2.PaperPortfolio.SerializeToString,
            ),
            'ListPaperPortfolios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPaperPortfolios,
                    request_deserializer=Portfolio__pb2.ListPaperPortfoliosRequest.FromString,
                    response_serializer=Portfolio__pb2.ListPaperPortfoliosResponse.SerializeToString,
            ),
            'GetPaperPortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaperPortfolio,
                    request_deserializer=Portfolio__pb2.GetPaperPortfolioRequest.FromString,
                    response_serializer=Portfolio__pb2.PaperPortfolioDetail.SerializeToString,
            ),
            'SubmitPaperWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitPaperWeights,
                    request_deserializer=Portfolio__pb2.SubmitPaperWeightsRequest.FromString,
                    response_serializer=Portfolio__pb2.PaperWeightSubmission.SerializeToString,
            ),
            'ListPaperPortfolioDailyResults': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPaperPortfolioDailyResults,
                    request_deserializer=Portfolio__pb2.ListPaperPortfolioDailyResultsRequest.FromString,
                    response_serializer=Portfolio__pb2.ListPaperPortfolioDailyResultsResponse.SerializeToString,
            ),
            'SettlePaperPortfolioDay': grpc.unary_unary_rpc_method_handler(
                    servicer.SettlePaperPortfolioDay,
                    request_deserializer=Portfolio__pb2.SettlePaperPortfolioDayRequest.FromString,
                    response_serializer=Portfolio__pb2.PaperPortfolioDailyResponse.SerializeToString,
            ),
            'SettleActivePaperPortfolios': grpc.unary_unary_rpc_method_handler(
                    servicer.SettleActivePaperPortfolios,
                    request_deserializer=Portfolio__pb2.SettleActivePaperPortfoliosRequest.FromString,
                    response_serializer=Portfolio__pb2.SettleActivePaperPortfoliosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LQTP.PortfolioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LQTP.PortfolioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PortfolioService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePaperPortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.PortfolioService/CreatePaperPortfolio',
            Portfolio__pb2.CreatePaperPortfolioRequest.SerializeToString,
            Portfolio__pb2.PaperPortfolio.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPaperPortfolios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.PortfolioService/ListPaperPortfolios',
            Portfolio__pb2.ListPaperPortfoliosRequest.SerializeToString,
            Portfolio__pb2.ListPaperPortfoliosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPaperPortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.PortfolioService/GetPaperPortfolio',
            Portfolio__pb2.GetPaperPortfolioRequest.SerializeToString,
            Portfolio__pb2.PaperPortfolioDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitPaperWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.PortfolioService/SubmitPaperWeights',
            Portfolio__pb2.SubmitPaperWeightsRequest.SerializeToString,
            Portfolio__pb2.PaperWeightSubmission.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPaperPortfolioDailyResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.PortfolioService/ListPaperPortfolioDailyResults',
            Portfolio__pb2.ListPaperPortfolioDailyResultsRequest.SerializeToString,
            Portfolio__pb2.ListPaperPortfolioDailyResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SettlePaperPortfolioDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.PortfolioService/SettlePaperPortfolioDay',
            Portfolio__pb2.SettlePaperPortfolioDayRequest.SerializeToString,
            Portfolio__pb2.PaperPortfolioDailyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SettleActivePaperPortfolios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.PortfolioService/SettleActivePaperPortfolios',
            Portfolio__pb2.SettleActivePaperPortfoliosRequest.SerializeToString,
            Portfolio__pb2.SettleActivePaperPortfoliosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
