# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Struct_pb2 as Struct__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Struct_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BacktestServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Backtest = channel.unary_stream(
                '/LQTP.BacktestService/Backtest',
                request_serializer=Struct__pb2.Request.SerializeToString,
                response_deserializer=Struct__pb2.DailyResponse.FromString,
                _registered_method=True)
        self.ListBacktestRuns = channel.unary_unary(
                '/LQTP.BacktestService/ListBacktestRuns',
                request_serializer=Struct__pb2.ListBacktestRunsRequest.SerializeToString,
                response_deserializer=Struct__pb2.ListBacktestRunsResponse.FromString,
                _registered_method=True)
        self.GetBacktestResult = channel.unary_unary(
                '/LQTP.BacktestService/GetBacktestResult',
                request_serializer=Struct__pb2.GetBacktestResultRequest.SerializeToString,
                response_deserializer=Struct__pb2.GetBacktestResultResponse.FromString,
                _registered_method=True)


class BacktestServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Backtest(self, request, context):
        """服务端流式：每处理完一个交易日即推送一条 DailyResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBacktestRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBacktestResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BacktestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Backtest': grpc.unary_stream_rpc_method_handler(
                    servicer.Backtest,
                    request_deserializer=Struct__pb2.Request.FromString,
                    response_serializer=Struct__pb2.DailyResponse.SerializeToString,
            ),
            'ListBacktestRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBacktestRuns,
                    request_deserializer=Struct__pb2.ListBacktestRunsRequest.FromString,
                    response_serializer=Struct__pb2.ListBacktestRunsResponse.SerializeToString,
            ),
            'GetBacktestResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBacktestResult,
                    request_deserializer=Struct__pb2.GetBacktestResultRequest.FromString,
                    response_serializer=Struct__pb2.GetBacktestResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LQTP.BacktestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LQTP.BacktestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BacktestService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Backtest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/LQTP.BacktestService/Backtest',
            Struct__pb2.Request.SerializeToString,
            Struct__pb2.DailyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBacktestRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.BacktestService/ListBacktestRuns',
            Struct__pb2.ListBacktestRunsRequest.SerializeToString,
            Struct__pb2.ListBacktestRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBacktestResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LQTP.BacktestService/GetBacktestResult',
            Struct__pb2.GetBacktestResultRequest.SerializeToString,
            Struct__pb2.GetBacktestResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
